# Generated by Django 5.1.6 on 2025-05-14 01:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hog', '0002_create_initial_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('Fellowship Sunday', 'Fellowship Sunday'), ('Christmas Carol Competition', 'Christmas Carol Competition'), ('Hallelujah Party', 'Hallelujah Party')], max_length=100)),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1)),
                ('year', models.IntegerField(default=2025)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(default='Main Auditorium', max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='monthly_events/')),
                ('coordinator_name', models.CharField(blank=True, max_length=200, null=True)),
                ('coordinator_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('coordinator_image', models.ImageField(blank=True, null=True, upload_to='monthly_events/coordinators/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['-year', 'month'],
                'unique_together': {('event_type', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyEventGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='monthly_events/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='hog.monthlyevent')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
