# Generated by Django 5.1.6 on 2025-05-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hog', '0003_monthlyevent_monthlyeventgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyeventgallery',
            options={'ordering': ['-date_added'], 'verbose_name_plural': 'Monthly Event Galleries'},
        ),
        migrations.AddField(
            model_name='monthlyeventgallery',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
