# Generated by Django 5.1.6 on 2025-05-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hog', '0004_alter_monthlyeventgallery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyevent',
            name='month',
            field=models.IntegerField(choices=[('January', 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1),
        ),
    ]
