# Generated by Django 5.1.6 on 2025-05-16 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hog', '0007_gallerycategory_galleryimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerycategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Gallery Categories'},
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
