# Generated by Django 5.1.6 on 2025-05-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hog', '0010_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
